[theme]
primaryColor="#FF6F00"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

[client]
toolbarMode = "minimal"

[server]
# Disable XSRF protection to fix upload issues
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false
maxUploadSize = 50
# Set a very long lifetime for sessions (7 days = 604800 seconds)
maxSessionAge = 604800
# Increase request timeout for larger file uploads
headless = false
runOnSave = false

[logger]
level = "warning"